version: "3.7"

services:
  store:
    container_name: store
    image: samply/blaze:latest
    environment:
      BASE_URL: "http://store:8080"
    ports:
      - "8080:8080"
  test-data-loader:
    container_name: test-data-loader
    image: samply/test-data-loader
    environment:
      FHIR_STORE_URL: "http://store:8080/fhir"
      PATIENT_COUNT: "2000"
      START_DELAY: 90
